import type { SignatureData } from './types';

function escapeTypst(str: string): string {
	return str
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/#/g, '\\#')
		.replace(/\$/g, '\\$')
		.replace(/@/g, '\\@');
}

function hexToTypstRgb(hex: string): string {
	return `rgb("${hex}")`;
}

export function generateTypstCode(data: SignatureData): string {
	const { name, pronouns, titles, email, phone, website, socialLinks, colors, fonts, layout } = data;
	const hasImage = !!(data.profileImageUrl || data.profileImage);
	const hasContact = !!(email || phone || website);
	const hasSocial = socialLinks.length > 0 && socialLinks.some((s) => s.url);
	const hasTitles = titles.some((t) => t.title || t.organization);

	// Map font family to a Typst-compatible font name
	const fontName = fonts.fontFamily.split(',')[0].replace(/['"]/g, '').trim();

	const borderRadius =
		layout.imageShape === 'circle'
			? '50%'
			: layout.imageShape === 'rounded'
				? '4pt'
				: '0pt';

	let code = `// Email Signature - Generated by Email Signature Maker
#set page(width: 500pt, height: auto, margin: 8pt)
#set text(font: "${fontName}", size: ${fonts.textSize}pt, fill: ${hexToTypstRgb(colors.textColor)})

`;

	// Signoff
	if (layout.showSignoff && layout.signoffText) {
		code += `#text(size: ${fonts.textSize}pt)[${escapeTypst(layout.signoffText)}]\n#v(8pt)\n\n`;
	}

	// Build the info content
	let infoContent = '';

	// Name
	if (name) {
		infoContent += `#text(size: ${fonts.nameSize}pt, weight: "bold", fill: ${hexToTypstRgb(colors.nameColor)})[${escapeTypst(name)}]`;
		if (pronouns) {
			infoContent += ` #text(size: ${fonts.textSize}pt, fill: ${hexToTypstRgb(colors.textColor)})[(${escapeTypst(pronouns)})]`;
		}
		infoContent += '\n';
	}

	// Divider after name
	if (name && (hasTitles || hasContact)) {
		if (layout.dividerStyle !== 'none') {
			const stroke = layout.dividerStyle === 'dashed'
				? `(dash: "dashed", paint: ${hexToTypstRgb(colors.dividerColor)}, thickness: 0.5pt)`
				: layout.dividerStyle === 'dotted'
					? `(dash: "dotted", paint: ${hexToTypstRgb(colors.dividerColor)}, thickness: 0.5pt)`
					: `0.5pt + ${hexToTypstRgb(colors.dividerColor)}`;
			infoContent += `#v(4pt)\n#line(length: 100%, stroke: ${stroke})\n#v(4pt)\n`;
		} else {
			infoContent += '#v(4pt)\n';
		}
	}

	// Titles
	const filteredTitles = titles.filter((t) => t.title || t.organization);
	for (const t of filteredTitles) {
		let titleText = '';
		if (t.title && t.organization) {
			titleText = `#text(size: ${fonts.titleSize}pt, fill: ${hexToTypstRgb(colors.titleColor)})[*${escapeTypst(t.title)}*, ${escapeTypst(t.organization)}]`;
		} else if (t.title) {
			titleText = `#text(size: ${fonts.titleSize}pt, fill: ${hexToTypstRgb(colors.titleColor)})[*${escapeTypst(t.title)}*]`;
		} else {
			titleText = `#text(size: ${fonts.titleSize}pt, fill: ${hexToTypstRgb(colors.titleColor)})[${escapeTypst(t.organization)}]`;
		}
		infoContent += `${titleText}\n`;
	}

	// Divider before contact
	if (hasContact && (hasTitles || name)) {
		if (layout.dividerStyle !== 'none' && hasTitles) {
			// Only add a second divider if we have titles (to avoid double divider)
		} else if (!hasTitles && !name) {
			// No divider needed
		}
		infoContent += '#v(4pt)\n';
	}

	// Contact info
	const contactParts: string[] = [];
	if (phone) {
		contactParts.push(`#link("tel:${escapeTypst(phone)}")[${escapeTypst(phone)}]`);
	}
	if (email) {
		contactParts.push(`#link("mailto:${escapeTypst(email)}")[${escapeTypst(email)}]`);
	}
	if (website) {
		const href = website.startsWith('http') ? website : `https://${website}`;
		const display = website.replace(/^https?:\/\//, '');
		contactParts.push(`#link("${escapeTypst(href)}")[${escapeTypst(display)}]`);
	}
	if (contactParts.length > 0) {
		infoContent += `#text(size: ${fonts.textSize}pt)[${contactParts.join(' | ')}]\n`;
	}

	// Social links (as text links in Typst - icons would require image files)
	if (hasSocial) {
		const socialParts = socialLinks
			.filter((s) => s.url)
			.map((s) => {
				const href = s.url.startsWith('http') ? s.url : `https://${s.url}`;
				return `#link("${escapeTypst(href)}")[${s.platform}]`;
			});
		if (socialParts.length > 0) {
			infoContent += `#v(2pt)\n#text(size: ${fonts.textSize}pt)[${socialParts.join(' #h(6pt) ')}]\n`;
		}
	}

	// Wrap in layout
	if (layout.layout === 'horizontal' && hasImage) {
		code += `#grid(
  columns: (${layout.imageSize}pt, 1fr),
  column-gutter: 16pt,
  box(
    clip: true,
    radius: ${borderRadius},
    width: ${layout.imageSize}pt,
    height: ${layout.imageSize}pt,
    image("photo.jpg", width: ${layout.imageSize}pt, height: ${layout.imageSize}pt, fit: "cover")
  ),
  [
${infoContent.split('\n').map(l => '    ' + l).join('\n')}
  ]
)\n`;
	} else if (layout.layout === 'stacked' && hasImage) {
		code += `#box(
  clip: true,
  radius: ${borderRadius},
  width: ${layout.imageSize}pt,
  height: ${layout.imageSize}pt,
  image("photo.jpg", width: ${layout.imageSize}pt, height: ${layout.imageSize}pt, fit: "cover")
)
#v(8pt)
${infoContent}`;
	} else {
		code += infoContent;
	}

	return code;
}
